<?php defined('INSTALL_DIR') or die('Permission deny!'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bjyadmin安装程序</title>
    <script type="text/javascript" src="static/js/jquery-2.0.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="static/bootstrap-3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/bootstrap-3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="static/font-awesome-4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/bjy.css">
    <script type="text/javascript" src="static/bootstrap-3.3.5/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="static/js/html5shiv.min.js"></script>
    <script type="text/javascript" src="static/js/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="static/css/install.css">
</head>